### ISSUE TITLE
Errors in new IntelliJ version

### ISSUE THREAD

**Issue by interone-ms** [mediaworx/opencms-intellijplugin#12]
Hi,

in the newest IntelliJ version ("Build #IU-242.20224.387, built on August 13, 2024"), the context menu actions (sync, pull metadata, ...) all do not work any more - the OpenCMS tab opens but stays at "Nothing to show" and these errors appear in the log:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.mediaworx.intellij.opencmsplugin.actions.menus.OpenCmsProjectPopupMenu' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: OpenCms]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by kaiwidmann** [comment]
I'll have a look at it, but probably not this week. I'm still on the previous version (Build #IU-241.19072.14, built on August 8, 2024), there still most things are working as expected.

**Comment by interone-ms** [comment]
@kaiwidmann there's more in the log file of IntelliJ and I think that one is the actual culprit:

```
2024-09-02 12:25:09,095 [352231468] SEVERE - #com.mediaworx.intellij.opencmsplugin.actions.sync.OpenCmsSyncSelectedAction - IntelliJ IDEA 2024.2.0.1  Build #IU-242.20224.387
2024-09-02 12:25:09,095 [352231468] SEVERE - #com.mediaworx.intellij.opencmsplugin.actions.sync.OpenCmsSyncSelectedAction - JDK: 21.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2024-09-02 12:25:09,095 [352231468] SEVERE - #com.mediaworx.intellij.opencmsplugin.actions.sync.OpenCmsSyncSelectedAction - OS: Mac OS X
2024-09-02 12:25:09,096 [352231469] SEVERE - #com.mediaworx.intellij.opencmsplugin.actions.sync.OpenCmsSyncSelectedAction - Plugin to blame: OpenCms version: 1.12.3
2024-09-02 12:25:09,096 [352231469] SEVERE - #com.mediaworx.intellij.opencmsplugin.actions.sync.OpenCmsSyncSelectedAction - Last Action: ShowLog
2024-09-02 12:25:09,097 [352231470]   INFO - #com.mediaworx.intellij.opencmsplugin.actions.sync.OpenCmsSyncAction - executeAction - event: com.intellij.openapi.actionSystem.AnActionEvent@64f8b577
2024-09-02 12:25:09,099 [352231472]   WARN - #com.mediaworx.intellij.opencmsplugin.actions.sync.OpenCmsSyncAction - Exception in OpenCmsSyncAction.actionPerformed: class javax.swing.ImageIcon cannot be cast to class com.intellij.openapi.util.ScalableIcon (javax.swing.ImageIcon is in module java.desktop of loader 'bootstrap'; com.intellij.openapi.util.ScalableIcon is in unnamed module of loader com.intellij.util.lang.PathClassLoader @546a03af)
java.lang.ClassCastException: class javax.swing.ImageIcon cannot be cast to class com.intellij.openapi.util.ScalableIcon (javax.swing.ImageIcon is in module java.desktop of loader 'bootstrap'; com.intellij.openapi.util.ScalableIcon is in unnamed module of loader com.intellij.util.lang.PathClassLoader @546a03af)
	at com.intellij.openapi.wm.impl.SquareStripeButton.updatePresentation(SquareStripeButton.kt:221)
	at com.intellij.toolWindow.ToolWindowPaneNewButtonManager$createStripeButton$manager$1.updateIcon(ToolWindowPaneNewButtonManager.kt:170)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.toolWindowPropertyChanged(ToolWindowManagerImpl.kt:2289)
	at com.jetbrains.rdserver.toolWindow.BackendServerToolWindowManager.toolWindowPropertyChanged(BackendServerToolWindowManager.kt:318)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.setIcon(ToolWindowImpl.kt:554)
	at com.mediaworx.intellij.opencmsplugin.OpenCmsPlugin.initToolWindow(OpenCmsPlugin.java:776)
	at com.mediaworx.intellij.opencmsplugin.OpenCmsPlugin.getConsole(OpenCmsPlugin.java:824)
	at com.mediaworx.intellij.opencmsplugin.actions.OpenCmsPluginAction.clearConsole(OpenCmsPluginAction.java:105)
	at com.mediaworx.intellij.opencmsplugin.actions.sync.OpenCmsSyncAction.executeAction(OpenCmsSyncAction.java:55)
	at com.mediaworx.intellij.opencmsplugin.actions.OpenCmsConnectionAction.actionPerformed(OpenCmsConnectionAction.java:50)
<snip>
```

There's other plugins affected by this as well: https://youtrack.jetbrains.com/issue/IJPL-49602/Icon-resizing-in-plugin-causes-ClasscastException and https://youtrack.jetbrains.com/issue/IJPL-160063/Start-Failed-class-javax.swing.ImageIcon-cannot-be-cast-to-class-com.intellij.openapi.util.ScalableIcon

Looks like some bad fuck-up with Java modules

**Comment by interone-ms** [comment]
Submitted a PR that at least makes the plugin work again after manually meddling with the artifact files. You will need to update to Java 17 and modules for the future, _possibly_ that was the cause all along as interop between stuff built in Java 8 and anything past that with modules is an insanely hot mess.

I'll do my best what I can if I get some time to fix up a couple of the issues and make it compile according to IntelliJ best practices, but please don't rely on that since I've gotta do that in my free time.

**Comment by interone-ms** [comment]
Here's the patched file. No guarantees of anything. [opencms-intellijplugin.zip](https://github.com/user-attachments/files/16836839/opencms-intellijplugin.zip)

**Comment by kaiwidmann** [comment]
Thanks for your effort, i'll try to have a look at it asap, I should be able to find the time tomorrow.

**Comment by interone-ms** [comment]
@kaiwidmann if you have some time to spare and you're touching the menu code anyway - do you see adding a "force push" and "force pull" button to the file/folder/editor tab menu possible? in my use case - creating formatters from inside IntelliJ - it would be really useful to pick up changes done exclusively inside opencms (=changing content type) without having to run through the whole "pull metadata" game.

**Comment by kaiwidmann** [comment]
Actually I don't really get it. If you use "SYNC" mode, changes are pulled or pushed based on the change date. Pulling medatata doesn't pull any changes (except for changed VFS properties). So I have some modules with formatters I'm working on either in OpenCms or on my local DEV repo and either way the right changes are synced based on the timestamp. You simply shouldn't change it on both sides, but force push/pull wouldn't help there.
Anyway, I get that force push/pull might be useful in some situations. So I'll add it to my list of future features and put it on top ;)

**Comment by interone-ms** [comment]
I don't use SYNC, it is (imho) too unreliable when dealing with multiple git branches and gets confused with changed file mtimes. Too much noise, at least with having PUSH being the default I can be reasonably sure that what is in git is also in OpenCMS.

Maybe SYNC could be modified to compare file contents and metadata, but ignore change times?

**Comment by kaiwidmann** [comment]
But without the dates, SYNC can only see that there are differences, the timestamp is needed to decide, which version is the most recent one. I usually work with PUSH exclusively, only when I create new content types I temporarily switch to SYNC (and only for the module) to pull new XSDs and formatters from the VFS. 
It works fine for me that way, but your method may differ. Anyway, I'll take a note of the Feature Request.

**Comment by kaiwidmann** [comment]
It's interesting, I don't see the class cast exception even though my code still uses the ImageIcon, the Tollwindow Icon is displayed (after the first activation of the OpenCms console). What system are you running on?

**Comment by kaiwidmann** [comment]
@interone-ms, could you check if the recent version fixes your problem. If so, I'll close this ticket.
